package ese.fragments;

import android.app.FragmentTransaction;
import android.net.Uri;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class MainActivity extends AppCompatActivity implements
        BookListFragment.OnFragmentInteractionListener,
        DetailsFragment.OnFragmentInteractionListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // == 01 we start in single pane mode replacing master and detail fragments as we need.
        // we build the Fragment on our own in order to be able to set the data
        // to be used
        // in this case we leave the Fragment code generated by the IDE in. Just for the fun of it.
//        if (savedInstanceState == null) {
//            BookListFragment bookListFragment = BookListFragment.newInstance("p1", "p2");
//
//            FragmentTransaction transaction = getFragmentManager().beginTransaction();
//            transaction.add(android.R.id.content, bookListFragment);
//            transaction.commit();
//        }

        // == 02 if show book is pressed we show the detail fragment
        // Add button to the book list fragment
        // Make button call onShowBook in this activity

        // == 03 if we have the fragment container present we show both fragments
        if (findViewById(R.id.details_fragment) != null) {
            
        }




    }

    @Override
    public void onShowBook(String title) {
        // == 02
        DetailsFragment detailsFragment = DetailsFragment.newInstance("p1", "p2");

        FragmentTransaction transaction = getFragmentManager().beginTransaction();
        transaction.replace(android.R.id.content, detailsFragment);
        transaction.addToBackStack(null);
        transaction.commit();

    }

    @Override
    public void onFragmentInteraction(Uri uri) {

    }
}
